// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKv47pTZgOjd5z5mXmyUl4nkUNSwVwqC4',
    appId: '1:2169475060:web:f8b600b24426c6499fb3a1',
    messagingSenderId: '2169475060',
    projectId: 'kajiwari-5ee2b',
    authDomain: 'kajiwari-5ee2b.firebaseapp.com',
    storageBucket: 'kajiwari-5ee2b.appspot.com',
    measurementId: 'G-C0JM4BNQZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUv33tV8emElYWJhKRXk0bK1Xp7uz8UxE',
    appId: '1:2169475060:android:26a09eb3493d27619fb3a1',
    messagingSenderId: '2169475060',
    projectId: 'kajiwari-5ee2b',
    storageBucket: 'kajiwari-5ee2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVmSqd79ZATDIqAQG5TCRW24vgcjpe7fg',
    appId: '1:2169475060:ios:8208788c940690ac9fb3a1',
    messagingSenderId: '2169475060',
    projectId: 'kajiwari-5ee2b',
    storageBucket: 'kajiwari-5ee2b.appspot.com',
    iosClientId: '2169475060-6q93dv8hh9fushluueehkqurl43opag9.apps.googleusercontent.com',
    iosBundleId: 'com.example.profieleWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVmSqd79ZATDIqAQG5TCRW24vgcjpe7fg',
    appId: '1:2169475060:ios:8208788c940690ac9fb3a1',
    messagingSenderId: '2169475060',
    projectId: 'kajiwari-5ee2b',
    storageBucket: 'kajiwari-5ee2b.appspot.com',
    iosClientId: '2169475060-6q93dv8hh9fushluueehkqurl43opag9.apps.googleusercontent.com',
    iosBundleId: 'com.example.profieleWeb',
  );
}
